<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-001'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-002'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-003'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-004'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-005'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-006'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-007'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-008'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-009'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-010'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-011'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-012'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-013'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-014'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-015'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-016'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-017'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-018'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-019'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-020'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-021'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-022'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-023'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-024'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-025'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-026'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-027'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-028'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-029'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-030'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-031'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-032'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-033'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-034'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-035'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-036'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-037'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-038'],
            ['class' => 'FG', 'zone' => 'A', 'code' => 'A-039'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-001'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-002'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-003'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-004'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-005'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-006'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-007'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-008'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-009'],
            ['class' => 'FG', 'zone' => 'B', 'code' => 'B-010'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-001'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-002'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-003'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-004'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-005'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-006'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-007'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-008'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-009'],
            ['class' => 'FG', 'zone' => 'C', 'code' => 'C-010'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-001'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-002'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-003'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-004'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-005'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-006'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-007'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-008'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-009'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-010'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-011'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-012'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-013'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-014'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-015'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-016'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-017'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-018'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-019'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-020'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-021'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-022'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-023'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-024'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-025'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-026'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-027'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-028'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-029'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-030'],
            ['class' => 'FG', 'zone' => 'D', 'code' => 'D-031'],
            ['class' => 'FG', 'zone' => 'E', 'code' => 'E-001'],
            ['class' => 'FG', 'zone' => 'E', 'code' => 'E-002'],
            ['class' => 'FG', 'zone' => 'E', 'code' => 'E-003'],
            ['class' => 'FG', 'zone' => 'E', 'code' => 'E-004'],
            ['class' => 'FG', 'zone' => 'E', 'code' => 'E-005'],
        ];

        DB::table('locations')->insert(array_map(function ($row) {
            return [
                'name' => $row['class'],
                'description' => $row['zone'],
                'code' => $row['code'],
                'qr_code' => $row['code'],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }, $rows));
    }
}
